### ISSUE TITLE
Deployment with github actions

### ISSUE THREAD

**Issue by alexwaeseperlman** [BioAnalyticResource/ePlant#23]
We should be able to host this on github pages, and automatically deploy with github actions. I implemented this once before, the workflow is [here](https://github.com/alexwaeseperlman/Pokerbots/blob/main/.github/workflows/deploy_doc.yml). 

Then maybe we can configure nginx on the bar to proxy the github pages. @asherpasha do you have thoughts on this?

**Comment by asherpasha** [comment]
I can host it on the BAR. It should be easier.

**Comment by alexwaeseperlman** [comment]
Have you tried enabling CD on the BAR? I'm not sure how that would look

**Comment by mwkyuen** [comment]
Closed. Work is completed.
