### ISSUE TITLE
ePlant Citation and Experiment Information is missing

### ISSUE THREAD

**Issue by nprovart** [BioAnalyticResource/ePlant#30]
### Citation and Experiment Button
![Capture](https://github.com/BioAnalyticResource/ePlant/assets/5684400/c18a119e-2704-45cf-8601-d767980d773b) - clicking on the Citation and Experiment Information button should open a modal / info pane that provides details on the experiment as per ePlant2.

### Citation and Experiment Modal
![Capture_2](https://github.com/BioAnalyticResource/ePlant/assets/5684400/0ecdb18d-7371-430e-9e74-04a0318ea198) - here is the info for the Klepikova Plant Viewer (see [here](https://bar.utoronto.ca/eplant/?ActiveSpecies=Arabidopsis%20thaliana&Genes=AT3G24650&ActiveGene=AT3G24650&ActiveView=KlepikovaView), click on the button...don't forget the CC BY licence info at the bottom!)

**Comment by mwkyuen** [comment]
Parent issue to #54 , and #55 .

**Comment by mwkyuen** [comment]
Can I get more info on where the citation information comes from? Is there a central source (like a eplant database), or is it dynamically generated each time.

**Comment by mwkyuen** [comment]
The CC By Licence button, does it have to be the same icon from eplant2?

**Comment by nprovart** [comment]
> The CC By Licence button, does it have to be the same icon from eplant2?

I'm not wedded to that icon!

**Comment by nprovart** [comment]
> Can I get more info on where the citation information comes from? Is there a central source (like a eplant database), or is it dynamically generated each time.

There is an XML file associated with each (eFP) view (e.g. for the meristemoids, the full path is https://bar.utoronto.ca/eplant/data/experiment/efps/GuardCellMeristemoids/Arabidopsis_thaliana.xml). This gets accessed using the efpXmlURL that gets generated in the Eplant.Views part of the app. The information that is between the <info> ... </info> tags of that XML file is displayed as Experiment and Citation info.
