### ISSUE TITLE
Masking of samples with high standard deviations

### ISSUE THREAD

**Issue by nprovart** [BioAnalyticResource/ePlant#33]
### Mask samples with high standard deviation
A modal pop-up in ePlant2 is used to set the standard deviation level above which samples are masked (greyed out). 
![Capture_4](https://github.com/BioAnalyticResource/ePlant/assets/5684400/aa0b49a1-5e11-4a09-8955-fc36cdbcf128)

**Comment by VinLau** [comment]
This button will turn on and off masking for coloured tissues. A further call-to-action ( a modal or tooltip with a percentage slider/input) after the button is pressed to specifiy the masking value. Masking is whereby a tissue (SVG) is not shown when a group.sterror >= group.mean * Eplant.maskThreshold (user set). Remember a group is a collection of replicates. So if the group's std error is 100 and the group mean value is 50 *2.1 (105), it will be masked.

Check source code [here](https://bar.utoronto.ca/eplant/src/Eplant.BaseViews/EFPView/Eplant.BaseViews.EFPView.js) (updateDisplay function) and [here](https://bar.utoronto.ca/eplant/src/Eplant.BaseViews/EFPView/Eplant.BaseViews.EFPView.js) for UI.

Note that the API returns values for a replicate but ultimately gets summarized as a mean value and a standard deviation is calculated. You can read those values.

**Comment by mwkyuen** [comment]
Parent issue to #51, #52, #53

**Comment by mwkyuen** [comment]
Bluk of work is done. Left grey colour to scale but that is captured in #49
