### ISSUE TITLE
Delete absolute information from tooltip in relative mode

### ISSUE THREAD

**Issue by zkdan** [BioAnalyticResource/ePlant#34]
For any view that has absolute and relative view modes, (cell view, tissue view, plant mode and maybe others),

ABSOLUTE view should NOT include "Log to full change" in the tooltip. Relative view should.

**Comment by VinLau** [comment]
To add on to removing the Log2 fold change to control, I think you'll have to track this via some state variable (whether abs or relative mode is on). See tootlip [code](https://github.com/BioAnalyticResource/ePlant/blob/3d76bc24f968aaf6a2132a4a4825b2233b7e50d2/Eplant/views/eFP/index.tsx#L32)
