### ISSUE TITLE
Reset pan/zoom not working in tissue/experiement view

### ISSUE THREAD

**Issue by zkdan** [BioAnalyticResource/ePlant#37]
To reproduce: open a gene in the Tissue & experimenter view. Zoom in on the image. Click `View Options > Reset pan/zoom`

**Comment by Yukthiw** [comment]
Closed with [27abed2296cde73550c69610e4d06e27323c8db3](https://github.com/BioAnalyticResource/ePlant/commit/27abed2296cde73550c69610e4d06e27323c8db3)
