### ISSUE TITLE
Weird scrollbars showing up in efp view

### ISSUE THREAD

**Issue by alexwaeseperlman** [BioAnalyticResource/ePlant#38]
![image](https://github.com/BioAnalyticResource/ePlant/assets/16113308/3c676271-762a-4dde-aeb5-5719c335fefd)

**Comment by mwkyuen** [comment]
@alexwaeseperlman is the intention to remove the 3 scroll bars that the arrow is pointing to?

**Comment by mwkyuen** [comment]
Closed by #48
