### ISSUE TITLE
Gene info panel: copy button for DNA + protein sequence

### ISSUE THREAD

**Issue by zkdan** [BioAnalyticResource/ePlant#39]
Adding a little copy button in the gutter  next to DNA sequence
<img width="1288" alt="Screenshot 2023-11-09 at 9 57 27 AM" src="https://github.com/BioAnalyticResource/ePlant/assets/7177924/27ed4d22-325a-4919-adc2-96ec0716af35">

**Comment by apiraam96** [comment]
Sounds good!

**Comment by VinLau** [comment]
> Sounds good!

Please assign yourself @apiraam96 ! 👍

**Comment by mwkyuen** [comment]
Closed. Work completed in #57
