### ISSUE TITLE
Add masked into scale

### ISSUE THREAD

**Issue by mwkyuen** [BioAnalyticResource/ePlant#49]
To reproduce:

1. Go to https://bioanalyticresource.github.io/ePlant/
2. Type in ABCC5 in the search box
3. Click the search icon
4. In the drop down, select Plant eFP
5. There is a scale diagram in the bottom left of the main panel

Desired outcome:
The scale should include a grey square in the lowest position that is labeled "Masked (>= 100% RSE)"
<img width="1398" alt="Screenshot 2023-11-23 at 4 26 15 PM" src="https://github.com/BioAnalyticResource/ePlant/assets/39020680/4a839d48-7282-45a3-9113-da79fa363125">
<img width="135" alt="Screenshot 2023-11-23 at 4 32 45 PM" src="https://github.com/BioAnalyticResource/ePlant/assets/39020680/011a3cd4-a695-44ee-81de-311658c6442f">

**Comment by VinLau** [comment]
The default value is >100% RSE (relative standard error) but it's actually not dynamic in ePlant2, we should make this dynamic such that when the user selects their threshold, the bottom grey box shall update. 

<img width="592" alt="image" src="https://github.com/BioAnalyticResource/ePlant/assets/22639326/c3ec1606-4f44-4b53-bd56-8bb03599e950">

I.e. the grey box would show 56% here. When the mask is NOT applied, we should also have a visual indicator. Thanks!

**Comment by mwkyuen** [comment]
Great tip. Thanks for elaborating on the issue!

**Comment by nprovart** [comment]
I don't think this has been pushed to Staging yet? I am seeing masked samples in the staging view, but not the corresponding grey in the legend saying "masked". Also the toggle doesn't seem to be working yet and there should probably be an indicator showing if "masked" has been selected?
![image](https://github.com/BioAnalyticResource/ePlant/assets/5684400/81bf42fa-6e36-449d-bee2-ce0136e33e0e)
