### ISSUE TITLE
Add labels to scale

### ISSUE THREAD

**Issue by mwkyuen** [BioAnalyticResource/ePlant#50]
To reproduce:

1. Go to https://bioanalyticresource.github.io/ePlant/
2. Type in ABCC5 in the search box
3. Click the search icon
4. In the drop down, select Plant eFP
5. There is a scale diagram in the bottom left of the main panel 
6. The scale only has labels for the lowest and the highest square tile

Desired outcome:
All tiles in the scale should have a label. Scale always has 11 + 1 (masked) tiles. The label values are X value apart. X is calculated by taking the max value divided by 11, and the label should be Max value - (X*tile number)
<img width="1398" alt="Screenshot 2023-11-23 at 4 26 15 PM" src="https://github.com/BioAnalyticResource/ePlant/assets/39020680/5ccacd97-5555-47b7-8cee-283526ae9c78">
<img width="135" alt="Screenshot 2023-11-23 at 4 32 45 PM" src="https://github.com/BioAnalyticResource/ePlant/assets/39020680/0b13c0bf-0a34-446d-b15a-c071463c8aa4">

**Comment by zkdan** [comment]
@VinLau, I've got a question: what is relative mode supposed to look like? Attached is what I've got currently.

![Image](https://github.com/BioAnalyticResource/ePlant/assets/7177924/a9a8cf14-e12f-48a1-af05-178659d28a2d)
![Image](https://github.com/BioAnalyticResource/ePlant/assets/7177924/532b4d6a-5840-4597-8db1-1c152eb639f1)

**Comment by zkdan** [comment]
Also, what's that last value there? The gray box with the >RSE?

**Comment by VinLau** [comment]
> @VinLau, I've got a question: what is relative mode supposed to look like? Attached is what I've got currently.

That's relative, relative means the expression levels are measured as a ratio: <DESIRED TISSUE>/<CONTROL>, <CONTROL> being either the median of all tissues or a specified control (like say an untreated leaf). Blue means it is lower relative to control, red means it is higher.

Masking means sometimes you want to hide really really high expression levels (like hide outliers in your data). See [here](https://github.com/BioAnalyticResource/ePlant/pull/63). RSE =  Relative standard error, kind of like standard deviation; >100% might be a default value chosen so outliers aren't show by default, I'll confirm with Nick. I think we might re-open that ticket and add a visual indicator like old eplant2.

@zkdan

**Comment by mwkyuen** [comment]
Hi Zoe. You are very close! Is it possible to display the numbers as floats (without rounding) instead of integers? Here is what the values are like from eplant2.

<img width="361" alt="Screenshot 2024-01-24 at 5 07 45 PM" src="https://github.com/BioAnalyticResource/ePlant/assets/39020680/649497cd-57fe-4735-b30a-e4da93488a83">

**Comment by mwkyuen** [comment]
The last value should be the grey box (which is currently not yet implemented; work detailed [here](https://github.com/BioAnalyticResource/ePlant/issues/49))

**Comment by zkdan** [comment]
Yep! I can do floats.
