### ISSUE TITLE
Clicking mask threshold will correctly affect the image displayed

### ISSUE THREAD

**Issue by mwkyuen** [BioAnalyticResource/ePlant#53]
Dependant on #52

To reproduce:

1. Go to https://bioanalyticresource.github.io/ePlant/
2. Type in ABCC5 in the search box
3. Click the search icon
4. In the drop down, select Plant eFP
5. In the top toolbar, click View Options
6. Click "Mask Data" from the dropdown (A modal popup should appear)
7. Set threshold to 10%

Desired outcome:
Clicking "Mask Threshold" should cause the modal to disappear, and the result is the images (main pollen, and leaf 6) on the main panel is greyed out. 
<img width="980" alt="Screenshot 2023-11-24 at 9 42 32 AM" src="https://github.com/BioAnalyticResource/ePlant/assets/39020680/4413b206-d466-484e-b536-d1af1fafead5">

**Comment by VinLau** [comment]
The formula to calculate the mask is [here](https://github.com/BioAnalyticResource/ePlant/issues/33#issuecomment-1815432627).
