### ISSUE TITLE
Convert GeneticElementComponent to pure css

### ISSUE THREAD

**Issue by alexwaeseperlman** [BioAnalyticResource/ePlant#8]
[`GeneticElementComponent`](https://github.com/BioAnalyticResource/ePlant/blob/7cdba082bbd22396dbbe6d2db9e42b1b73d14ebb/Eplant/UI/GeneticElementComponent.tsx#L88) currently uses javascript to update styles when hovered. It is probably possible to make it use pure css instead, which might make the code cleaner.

**Comment by mwkyuen** [comment]
Closing for now in favour of higher priority work
