### ISSUE TITLE
Collapsable side panel

### ISSUE THREAD

**Issue by nprovart** [BioAnalyticResource/ePlant#86]
It would be nice to be able to collapse the left side panel either using a "burger" (three horizontal lines) or left arrow icon. Even after Jamie's modification to its width, it is still quite wide...
![image](https://github.com/BioAnalyticResource/ePlant/assets/5684400/55b0f9c4-8490-4bc2-b4b5-8c40b6985bac)

**Comment by jamiewaese** [comment]
this may be less important than before... I just pushed an update reducing the side panel to 240px...

**Comment by VinLau** [comment]
Hi @apiraam96 , good job on getting this going. Here is the suggestion I propose to make your button more clear. Draw a semi-circle that seems to connect to the main pane so the user intuitively thinks this button pulls or pushes the pane wider/smaller.
Before vs After

![image](https://github.com/BioAnalyticResource/ePlant/assets/22639326/cc7ba1e6-473d-4975-a040-5f76ae329be2)

<img width="511" alt="image" src="https://github.com/BioAnalyticResource/ePlant/assets/22639326/c2c47cce-daf2-4437-a9ae-a0e2c2ed3102">
